name: ADLC3 CA
# https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
on:
  push:
   # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet   
    branches:
      - 'release/v[0-9]+.[0-9]+'
      # Condition to check if commit message starts with #NORUN is on line 14
      
jobs:
  adlc_workflow:
    runs-on: ubuntu-latest
    # If commit message starts with #NORUN, it will not be triggered
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"

    steps:

    # Source: https://github.com/marketplace/actions/setup-go-environment
    - name: checkout-source
      uses: actions/checkout@v3

    - name: Echo email
      run: echo ${{ env.EMAIL }}

    - name: Echo repo link
      run: echo ${{ env.REPO_URL }}
