name: ADLC3_CA_CWQ

on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+'
    # The code to check if commit message starts with #NORUN is in line 11
      
jobs:
  adlc_workflow:
    # If the commit message starts with #NORUN, it will not be triggered
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest

    steps:
    # Checkout 
    - name: checkout-source
      uses: actions/checkout@v3

    # Workflow to Deploy Railway
    - name: Deploy railway
      uses: bervProject/railway-deploy@main
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      with:
        service: ${{ secrets.RAILWAY_SERVICE }}

    # Send notification to slack chat
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # Posting block kit message from slack 
        payload: |
          {
            "blocks": [
              {
                "type": "divider"
              },
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA 56 CI/CD Submission"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* ${{ secrets.USERNAME }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:* <mailto:${{ secrets.EMAIL }}|${{ secrets.EMAIL }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:* ${{ secrets.MATRICULATION_NUMBER }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": " "
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.server_url }}/${{ github.repository }}|${{ github.server_url }}/${{ github.repository }}>"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ secrets.RAILWAY_LINK }}"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": true
                  },
                  "value": "Go",
                  "url": "${{ secrets.RAILWAY_LINK }}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
