name: ADLC3_CA
# https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
on:
  push:
   # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet   
    branches:
      - 'release/v[0-9]+.[0-9]+'
      # Condition to check if commit message starts with #NORUN is on line 14
      
jobs:
  adlc_workflow:
    runs-on: ubuntu-latest
    # If commit message starts with #NORUN, it will not be triggered
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"

    steps:

    # Source: https://github.com/marketplace/actions/setup-go-environment
    - name: checkout-source
      uses: actions/checkout@v3

    - name: Echo email
      run: echo ${{ env.EMAIL }}

    - name: Echo repo link
      run: echo ${{ env.REPO_URL }}

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # Posting block kit message from slack 
        payload: |
          {
            "blocks": [
              {
                "type": "divider"
              },
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA56 CI/CD Submission"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* Chan Wei Quan"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:* <mailto:${{ secrets.EMAIL }}|${{ secrets.EMAIL }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:* A0269482N"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": " "
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.server_url }}|${{ github.repository }}>"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "INSERT RAILWAY LINK HERE"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": true
                  },
                  "value": "click_me_123",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
